sudo: required
services:
  - docker

before_install:
  # ./client in the end, usually it was just ./ now we are saying for test content look at client folder
  # because our location is different
  # . - means = look at the current directory
  - docker build -t 19911226/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true 19911226/react-test npm test

after_success:
  - docker build -t 19911226/multi-client ./client
  - docker build -t 19911226/multi-nginx ./nginx
  - docker build -t 19911226/multi-server ./server
  - docker build -t 19911226/multi-worker ./worker
  # Log in to the CLI, 1 part will extract password
  #  2, after | => will insert password as second command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take thous images and push them to docker hub
  # docker tag local-image:tagname new-repo:tagname
  # docker push 19911226/tretiak:tagname

  - docker push 19911226/multi-client
  - docker push 19911226/multi-nginx
  - docker push 19911226/multi-server
  - docker push 19911226/multi-worker

deploy:
  # AWS
  provider: elasticbeanstalk
  # region in ou AWS url
  region: "us-east-1"
  #  Name of hte app
  app: "multi-docker"
  #  EnV name
  env: "MultiDocker-env"
  # Travis take all our file from the  github repository, zip
  # and copy to S3 bucket. after travis ping elasticbeanstalk
  # and notify that file uploaded
  bucket_name: "elasticbeanstalk-us-east-1-591291188791"
  # the same as app name, name of the folder in the bucket_name folder
  bucket_path: "docker-multi"
  # Deploy application only from master branch
  on:
    branch: master
  # IAM Amazon service that manage API keys, hosted on travis
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
