version: "3"
services: 
  postgres:
  # db, 
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    # Because nginx must run in any situation
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      # will map port in our local machine to nginx port
      - '3050:80'
  api:
    build:
      # Only name of the dockerfile not a path to this file 
      dockerfile: Dockerfile.dev
      # path to docker file
      context: ./server
    volumes: 
      # Do not try to override this folder 
      - /app/node_modules
      # ref to our project, will reload on change event in this folder
      # everything in this folder will be shared with app folder inside the container
      - ./server:/app
    environment: 
      # Docker will look at service redis/other, we do not need ane additional links
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
 


    

  
